doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            uuid: App\SharedContext\Doctrine\Type\UuidType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\BookingContext:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/BookingContext/Entity'
                prefix: 'App\BookingContext\Entity'
                alias: App\BookingContext
            App\NotificationContext:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/NotificationContext/Entity'
                prefix: 'App\NotificationContext\Entity'
                alias: App\NotificationContext
            App\PaymentContext:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/PaymentContext/Entity'
                prefix: 'App\PaymentContext\Entity'
                alias: App\PaymentContext
            App\ReviewContext:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/ReviewContext/Entity'
                prefix: 'App\ReviewContext\Entity'
                alias: App\ReviewContext
            App\ServiceManagementContext:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/ServiceManagementContext/Entity'
                prefix: 'App\ServiceManagementContext\Entity'
                alias: App\ServiceManagementContext
            App\UserManagementContext:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/UserManagementContext/Entity'
                prefix: 'App\UserManagementContext\Entity'
                alias: App\UserManagementContext
        controller_resolver:
            auto_mapping: true

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
